### PR TITLE
Implement changes based on data review for csn temp/wind

### PR DESCRIPTION
**Pull request by ekman-kaur**
**Feedback provided by Bridget**
nps.noaa_cns_temp.b0.*
1.	Both air_temperature & uncorrected_air_temperature have many values of 999999.0. I’m not sure if those are actually supposed to be the _FillValue of -9999. They are flagged as good in the qc variable, which doesn’t seem correct.
2.	It’s unclear to me what the number_of_records_average_* variables represent. If they are the number of records, then I would expect whole numbers and an integer datatype (like the cns_wind file). If the values are the average of the number of records, then over what period? Also, in either case, I would not expect negative values, which are present in the two that relate to temperature.
3.	The three SNR_average_* variables contain only the _FillValue. These are all flagged as bad in the qc variable, so maybe it’s ok. I just don’t know.

nps.noaa_cns_wind.b0.*
1.	I would change the description global attribute to read as "Converting Cns wind data from ascii text to netCDF"
2.	The wind_direction and wind_speed variables have many values of 999999.0. I’m not sure if those are actually supposed to be the _FillValue of -9999. They are flagged as good in the qc variable, which doesn’t seem correct.

### CODE REVIEW

**Comment by jmcvey3** [comment]
Instead of just changing the datatype to integer, I would go back and actually look up what number_of_records_average_* variables represents

**Comment by ekman-kaur** [comment]
> Instead of just changing the datatype to integer, I would go back and actually look up what number_of_records_average_* variables represents
@jmcvey3 the variables are following:
image

changed it to int because it is a count var in the input file and should be whole number in my perspective.

**Comment by ekman-kaur** [comment]
> Instead of just changing the datatype to integer, I would go back and actually look up what number_of_records_average_* variables represents

@jmcvey3 the variables are following:
number_of_records_average_uncorrected_RASS_temperature
number_of_records_average_corrected_RASS_temperature
number_of_records_average_vertical_wind

image

changed it to int because it is a count var in the input file and should be whole number in my perspective.

**Comment by jmcvey3** [comment]
Oh, I see. Well then nevermind, carry on

**Comment by jmcvey3** [comment]
> > Instead of just changing the datatype to integer, I would go back and actually look up what number_of_records_average_* variables represents
> 
> @jmcvey3 the variables are following: number_of_records_average_uncorrected_RASS_temperature number_of_records_average_corrected_RASS_temperature number_of_records_average_vertical_wind
> 
> image
> 
> changed it to int because it is a count var in the input file and should be whole number in my perspective.

Oh, I see. Well then nevermind, carry on

**Review by jmcvey3 — APPROVED** [review]

**Comment by jmcvey3** [comment]
Would also recommend updating requirements.txt with to get the tests passing again.

netCDF4<=1.6.5
numpy<=1.26.4
numexpr<=2.10.0
scipy<1.14.0

**Pull request merged**
